server:
  port: 9191
spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false
      uri: http://localhost:9296
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      httpclient:
        connect-timeout: 50000
        response-timeout: 50000
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: fornecedor
          uri: lb://fornecedor
          predicates:
            - Path=/info/**, /pedido/**, /produto/**

        - id: loja
          uri: lb://loja
          predicates:
            - Path=/compra/**

        - id: transportador
          uri: lb://transportador
          predicates:
            - Path=/entrega/**
  config:
    use-legacy-processing:


management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
